=head1 BRRRRZZZZZZZZZZZZZZZZNAME

vuvuzela.pl - Introduce the sounds of African football culture into IRC with irssi.

=head1 BBRRZZZZZZZUSAGE

Stick it into your C< ~/.irssi/scripts/ > folder and then start it up by running: C< /run vuvuzela >

=head1 BRRZZZZZZZZZZZZCOMMANDS

=head2 /vvz [some text]

Feed it something to say. It'll make you sound like you're blowing your trumpet a lot. 
The more you say, the more you are blowing your own trumpet.

=head2 /vuvuzela [number]

Give it a number. The bigger the number, the more carried away it gets. Enough said.

=head1 BBRRZZZZZREQUIREMENTS

A modern copy of irssi and a few bouncers to help avoid zealous ops.

=head1 BBRRRRRZZZZZZLICENSE

This program is free software. It comes without any warranty, to the extent permitted by applicable law. 
You can redistribute it and/or modify it under the terms of the Do What The Fuck You Want To Public License, 
Version 2, as published by Sam Hocevar. See http://sam.zoy.org/wtfpl/COPYING for more details. 

=cut

